export const DEFAULT_CLIENTS = [
  { name: "Nokia",            logo: "/clients/Nokia 1.svg",                           whiteBg: false, order: 0,  visible: true },
  { name: "Saudi Aramco",     logo: "/clients/Aramco.png",                            whiteBg: false, order: 1,  visible: true },
  { name: "Philips",          logo: "/clients/Philips_logo.png",                      whiteBg: true,  order: 2,  visible: true },
  { name: "Alfanar",          logo: "/clients/Alfanar Projects_Logo-1.png",           whiteBg: false, order: 3,  visible: true },
  { name: "Ford",             logo: "/clients/FORD .png",                             whiteBg: false, order: 4,  visible: true },
  { name: "Leap",             logo: "/clients/Leap.jpg",                              whiteBg: true,  order: 5,  visible: true },
  { name: "GACA",             logo: "/clients/GACA LOGO 1.png",                       whiteBg: false, order: 6,  visible: true },
  { name: "UAPM",             logo: "/clients/UAPM-Logo(Property Management Co).png", whiteBg: false, order: 7,  visible: true },
  { name: "SEA Expo",         logo: "/clients/SEA-Expo-logo-Master-03.png",           whiteBg: true,  order: 8,  visible: true },
  { name: "Huawei",           logo: "/clients/Huawei.png",                            whiteBg: false, order: 9,  visible: true },
  { name: "Neom",             logo: "/clients/Neom-Logo.png",                         whiteBg: false, order: 10, visible: true },
  { name: "Red Hat",          logo: "/clients/Red_Hat_Logo_2019.svg.png",             whiteBg: true,  order: 11, visible: true },
  { name: "SEC",              logo: "/clients/SEC_Logo.png",                          whiteBg: false, order: 12, visible: true },
  { name: "Rawabi",           logo: "/clients/Rawabi_2023_Logo_uniform_11.png",       whiteBg: false, order: 13, visible: true },
  { name: "AFZCO",            logo: "/clients/AFZCO-LOGO-2020-FINAL.png",             whiteBg: false, order: 14, visible: true },
  { name: "Al Jazirah",       logo: "/clients/ALJAZIRAH LOGO PNG.png",                whiteBg: false, order: 15, visible: true },
  { name: "10X",              logo: "/clients/10X Logo 2.png",                        whiteBg: false, order: 16, visible: true },
  { name: "Autoville",        logo: "/clients/Autoville.png",                         whiteBg: false, order: 17, visible: true },
  { name: "Defence Show",     logo: "/clients/Defence show.png",                      whiteBg: false, order: 18, visible: true },
  { name: "Dezerta",          logo: "/clients/Dezerta Logo.png",                      whiteBg: false, order: 19, visible: true },
  { name: "FHM",              logo: "/clients/FHM 1.png",                             whiteBg: false, order: 20, visible: true },
  { name: "Mansam",           logo: "/clients/Mansam logo-bilingual Final.png",       whiteBg: false, order: 21, visible: true },
  { name: "Mega Group",       logo: "/clients/Mega-Group.png",                        whiteBg: false, order: 22, visible: true },
  { name: "Modn Annan",       logo: "/clients/Modn-ANnan.png",                        whiteBg: false, order: 23, visible: true },
  { name: "Nahdah FC",        logo: "/clients/Nahdah FC.png",                         whiteBg: false, order: 24, visible: true },
  { name: "National Grid SA", logo: "/clients/Nationl Grid .SA .png",                 whiteBg: false, order: 25, visible: true },
  { name: "PDC",              logo: "/clients/PDC.png",                               whiteBg: false, order: 26, visible: true },
  { name: "Polaris",          logo: "/clients/POLARIS.png",                           whiteBg: false, order: 27, visible: true },
  { name: "Aramco Iktva",     logo: "/clients/ShareLogo.jpg",                         whiteBg: true,  order: 28, visible: true },
  { name: "Unified",          logo: "/clients/UNIFIED-LOGO.png",                      whiteBg: false, order: 29, visible: true },
  { name: "All Jerry",        logo: "/clients/all jerry logo 02.png",                 whiteBg: false, order: 30, visible: true },
  { name: "BH",               logo: "/clients/bh_logo_black_onwhite.png",             whiteBg: true,  order: 31, visible: true },
  { name: "State Grid",       logo: "/clients/state_grid.png",                        whiteBg: false, order: 32, visible: true },
  { name: "Glamping",         logo: "/clients/glamping_80cm_80cm.png",                whiteBg: false, order: 33, visible: true },
  { name: "One Mic",          logo: "/clients/one mic.png",                           whiteBg: false, order: 34, visible: true },
  { name: "Riyadh Diamond",   logo: "/clients/riyadh dimond.png",                     whiteBg: false, order: 35, visible: true },
  { name: "7D",               logo: "/clients/7d logo .png",                          whiteBg: false, order: 36, visible: true },
  { name: "Apotheek",         logo: "/clients/APOTHEEK.png",                          whiteBg: false, order: 37, visible: true },
  { name: "Almosa",           logo: "/clients/Almosa H.jpg",                          whiteBg: true,  order: 38, visible: true },
] as const;
